name: Build all

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
    branches:
      - main
      - "release/**"
      - "hotfix/**"
  workflow_dispatch:
  workflow_call:
    inputs:
      targetBranchName:
        required: true
        type: string

jobs:
  # Create new tag.
  buildAl:
    name: Build all
    runs-on: ubuntu-latest
    steps:
      # Print variables for logging and debugging purposes.
      - name: Print Env Vars
        run: |
          echo Git ref_name: ${{ github.ref_name }}
          echo Git run_number: ${{ github.run_number }}
          echo Git event_name: ${{ github.event_name }}
          echo Git targetBranchName: ${{ inputs.targetBranchName }}

      # Define target branch name.
      - name: Define target branch name
        uses: haya14busa/action-cond@v1
        id: defineTargetBranchName
        with:
          cond: ${{ inputs.targetBranchName != '' }}
          if_true: ${{ inputs.targetBranchName }}
          if_false: ${{ github.ref_name }}

      # Define version name (e.g. v1.0.0+123).
      - name: Define version name
        id: extractBranchName
        uses: actions/github-script@v6
        with:
          script: return "${{ steps.defineTargetBranchName.outputs.value }}".replace("release/", "").replace("hotfix/", "");
          result-encoding: string

      # Create tag
      - name: Create tag
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.defineTargetBranchName.outputs.value }}
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag "${{ steps.extractBranchName.outputs.result }}+${{ github.run_number }}"
          git push origin "${{ steps.extractBranchName.outputs.result }}+${{ github.run_number }}"

        # Do the build
      - name: Build
        run: |
          echo version: ${{ steps.extractBranchName.outputs.result }}+${{ github.run_number }}
