name: Create Release/Hotfix Branch (2)

on:
  workflow_dispatch:
    inputs:
      commitSHA:
        description: "Commit SHA reference"
        required: true
        type: string
      bumb:
        description: "Select the version. 'patch' and 'prepatch' will generate a hotfix branch, any other options will generate a regular release."
        required: false
        default: "minor"
        type: choice
        options:
          - prerelease
          - major
          - premajor
          - minor
          - preminor
          - patch
          - prepatch
      releaseType:
        description: "Select the release type. By default, only a tag will be created. If you want to create a release with the tag select the type."
        type: choice
        required: false
        options:
          - noRelease
          - draft
          - publish

jobs:
  # Print variables for logging and debugging purposes
  checkEnv:
    name: Check Env variables
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Print Env Vars
        run: |
          echo Git Base Ref: ${{ github.base_ref }}
          echo Git Pull Request Ref: ${{ inputs.commitSHA }}
          echo OC CLI Version: $(oc version)

  createRelease:
    name: "Create release"
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: checkEnv
    steps:
      # Define if the relase is a regular release or a hotfix.
      - name: Define release or hotfix
        uses: haya14busa/action-cond@v1
        id: releaseOrHotfix
        with:
          cond: ${{ github.event_name == 'workflow_dispatch' && (inputs.bumb == 'patch' || inputs.bumb == 'prepatch') }}
          if_true: hotfix
          if_false: release
      - run: |
          echo "Release type: ${{ steps.releaseOrHotfix.outputs.value }}"

      - name: Get bumb value
        uses: haya14busa/action-cond@v1
        id: getBumb
        with:
          cond: ${{ github.event_name == 'workflow_dispatch'}}
          if_true: ${{ inputs.bumb }}
          if_false: "prerelease"

      - name: Get preId value, if provided
        uses: haya14busa/action-cond@v1
        id: getPreId
        with:
          cond: ${{ github.event_name == 'workflow_dispatch' && (inputs.bumb == 'premajor' || inputs.bumb == 'preminor' || inputs.bumb == 'prepatch' || inputs.bumb == 'prerelease') }}
          if_true: ${{ inputs.bumb }}
          if_false: "prerelease"

      # Create the branch
      - name: Checkout branch
        uses: actions/checkout@v3
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b "${{ steps.releaseOrHotfix.outputs.value }}/${{ steps.releaseOrHotfix.outputs.value }}"
          git push --set-upstream origin "${{ steps.releaseOrHotfix.outputs.value }}/${{ steps.releaseOrHotfix.outputs.value }}"

      # Create the tag
      - name: "Create tag"
        id: createNextTag
        uses: zwaldowski/semver-release-action@v3
        with:
          prefix: "v"
          bump: ${{ steps.getBumb.outputs.value }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          per_branch: true
      - run: echo "Tag ${{ steps.createNextTag.outputs.version_tag }} created!"
