name: Create Release/Hotfix Branch

on:
  workflow_dispatch:
    inputs:
      gitRef:
        description: "Git Ref (e.g. v0.0.0-prerelease.45)"
        required: true
        default: ""
      releaseType:
        description: "Select the release type."
        type: choice
        required: false
        options:
          - release
          - hotfix
      releaseOption:
        description: "Release option"
        required: true
        default: "preminor"
        type: choice
        options:
          - premajor
          - preminor
          - prepatch
      versionName:
        description: "Version name (must follow e.g. v1.0.0)"
        required: true
        default: ""

jobs:
  createRelease:
    name: "Create release/hotfix"
    runs-on: ubuntu-latest
    steps:
      # Print variables for logging and debugging purposes
      - name: Print Env Vars
        run: |
          echo Git Base Ref: ${{ github.base_ref }}
          echo Git Pull Request Ref: ${{ inputs.gitRef }}

      # Create the branch
      - name: Create branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.gitRef }}
          fetch-depth: 0
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b "${{ inputs.releaseType }}/${{ inputs.versionName }}"
          git push --set-upstream origin "${{ inputs.releaseType }}/${{ inputs.versionName }}"
          git tag "${{ inputs.versionName }}-${{ inputs.releaseOption }}.0""
          git push
