name: Create Release/Hotfix tag on new branches

on:
  push:
    branches:
      - "release/*"
      - "hotfix/*"

jobs:
  createRelease:
    name: "Create release/hotfix"
    runs-on: ubuntu-latest
    steps:
      # Print variables for logging and debugging purposes
      - name: Print Env Vars
        run: |
          echo Git Base Ref: ${{ github.base_ref }}
