name: Create Release/Hotfix Branch

on:
  workflow_dispatch:
    inputs:
      gitRef:
        description: "Git Ref (e.g. main+456)"
        required: true
        default: ""
      releaseType:
        description: "Select the release type."
        type: choice
        required: false
        options:
          - release
          - hotfix
      versionName:
        description: "Version name (must follow e.g. v1.0.0)"
        required: true
        default: "v0.0.0"

jobs:
  createRelease:
    name: "Create release/hotfix"
    runs-on: ubuntu-latest
    steps:
      # Print variables for logging and debugging purposes
      - name: Print Env Vars
        run: |
          echo Git Base Ref: ${{ github.base_ref }}
          echo Git Pull Request Ref: ${{ inputs.gitRef }}

      # Create the branch.
      - name: Create branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.gitRef }}
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b "${{ inputs.releaseType }}/${{ inputs.versionName }}"
          git push --set-upstream origin "${{ inputs.releaseType }}/${{ inputs.versionName }}"
  buildAll:
    # Executes the first build on the new branch.
    needs: createRelease
    name: Buil all
    uses: ./.github/workflows/build-all.yml
    with:
      targetBranchName: "${{ inputs.releaseType }}/${{ inputs.versionName }}"
    secrets: inherit
